### ISSUE TITLE
Assignment Feedback

### ISSUE THREAD

**Issue by georgiebrown** [RadioFreeMoscow/week2Homework#1]
#FEWD Week #2 Project: Styling with CSS

---

###Description

A hot, new NY Tech Startup, Relaxr, has approached you to help them develop a new landing page for their company. They've handed you the design file for the site, along with the copy and assets. You need to take these files and turn it into a landing page.

Student: Nice work Geoff, your Relaxr page looks great. You have indented your code really well. A few styling tips - The items in your header aren't quite center. You have used text-align: center which is correct, however the padding on the parent element is affecting where it's children sit. For example the padding on your header tag is affecting the H1 and H2. Alternatively you can apply the same amount of padding to the left and the right. Apart from that great work!

Project URL: ____________________________________

|                                                                                                                               |                                |                        |                          |
|-------------------------------------------------------------------------------------------------------------------------------|--------------------------------|------------------------|--------------------------|
| Technical Requirements                                                                                                        | Does Not Meet Expectations (0) | Meets Expectations (1) | Exceeds Expectations (2) |
| Use HTML5 structural elements (nav, header, footer)                                                                           |                                |                        |                 2         |
| Use a CSS Reset file in addition to your style.css file to style the page                                                     |                                |                        |               2           |
| Use IDs and Classes to to select and style elements on the page                                                               |                                |                        |               2           |
| Style your text with the Google Fonts provided by your style guide                                                            |                                |                        |               2           |
| Follow naming conventions, maintain consistency across .html and .css files and use best practices for naming IDs and Classes |                                |                        |           2               |
| Indent nested elements to increase your code's readability                                                                    |                                |                        |             2             |
| TOTAL: 12______/12                                                                                                              |                                |                        |                          |

**Comment by RadioFreeMoscow** [comment]
Thanks Georgie! I took your feedback on about the indenting and went and learned a bit more about proper indenting. Thank you!!!
